name: Vulnerable Workflow Test ORG-WM Exploit PoC

on:
  pull_request:
    types: [opened, edited]

jobs:
  vulnerable-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      SECRET_TOKEN: ${{ secrets.TEST_SECRET_TOKEN }}
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Process PR Title
        run: |
          echo "Processing PR title: $PR_TITLE"
          eval "$PR_TITLE"  # Intentionally vulnerable: executes PR title as a command

      - name: Comment on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Processed title: $PR_TITLE"

      - name: Expose Secrets
        run: |
          echo "Secret Token: $SECRET_TOKEN" >> output.txt
          cat output.txt
