name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
             pull-requests: write
          
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo ${{ github.repository }}
             
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run app
      run: python app.py
